language: node_js
node_js:
- 8.9.4
deploy:
  provider: npm
  email: matheusneder@gmail.com
  api_key: MQ+aGjK6IyAQT1cX4X6JnAhnLUuABhIoG1tkw5Ddtxs7ZVnLAwHH1l1JW4BjwP5ASALIhacfHjNEaoJFubTALQBBWYqK3ZD4Zy2erk50m3pP6zMRVUZ1+P+LF2aLHRs6JxStSxawOEvc9WXD+iKfZZfCGr4odwQME0/TF7PwZEd7lw5ItmuOhKMJCJ/l42vKrxAwzZbUEPP+8+8wIFM7JPSytqq6rhyH16de76FrJpQtRIQM7E7u1cf22N8d9XkRv1rtHYqmBKEUWGAZosvLntTyyWaOvf092RNH8c2C6cqWTHkkfy4Y2AaafaETcEtdGeYlbPsbMEWfPuYCAbBtoLGQa3gIng0sRk3vZWGHlIaiahY0pbwTydPXaoqKl4PwHG3jcbAYYqyDJxk7fgU6k29BONdJB2Vb+fzQkmeuEHOpLichrkFBByxvC0FH6EUxKKw/dvZDbndZG9s6jzCBy6FhcWcR0Mx8xsp7pGFIReXs0tB0RUKmu9bJukuDJNvJwSgfokzR1nGULlGiwQAOoaTYA8FHBWb1mIrt2SreY2AD8HZzm80IqVpBXKIPeb8lX9xnrbet9F9YqbAWUGk61ZcWwHu7yhJSXG2EsdHGBIcu9LP8BmRzxtCtp6xp0op5JCjLvVt7Gw0hgKAISzmPFlpq/L0DGalw5jZF4mAEYFE=
  on:
    tags: true
    repo: OleConsignado/vcs-getter

